---
title: "Angola Data"
author: "Samuel Lowry"
date: "11/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(janitor)
library(reshape2)
library(tidyverse)
```

```{r angola_data}
# I read in the partially cleaned data attained from https://data.worldbank.org/country/angola?view=chart

angola_data <- read.csv("angola/angola_worldbank_data.csv")

#I then deleted all years past 2015 as my WHO data only goes until 2015
  
angola_data <- angola_data[ -c(2, 19:22) ] %>% 
  na.omit() 


# The problem here is that once the data was imported, the years came up with x in front of them, so I renamed them all. 

names(angola_data) <- c("metric", 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015)

# I then melted based upon the metric to get the year into a column instead of row. 

angola_data <- angola_data %>% 
  melt(id.vars = "metric") 

#I gave the columns better names

names(angola_data) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

angola_data <- angola_data %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = year + 1999) %>% 
  arrange(year)
```


```{r adult_mortality_angola}
# data source: http://apps.who.int/gho/data/view.main.1360?lang=en and I got rid of the first row because it was for 2016, and we are just working with 2000-2015

adult_mortality_angola <- read.csv("angola/adult_mortality_angola.csv") 
adult_mortality_angola = adult_mortality_angola[-1, ]

#I then specified what everything was and formatted the year.

adult_mortality_angola <- adult_mortality_angola %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  arrange(year)
```

```{r gdp_angola}
# data source: http://apps.who.int/gho/data/node.main.GHEDGGHEDGDPSHA2011?lang=en

gdp_angola <- read.csv("angola/gghe-d_gdp_angola.csv") 

# The problem here is that once the data was imported, the years came up with x in front of them, so I renamed them all.

names(gdp_angola) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

gdp_angola <- gdp_angola %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(gdp_angola) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

gdp_angola <- gdp_angola %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = 2016 - year) %>% 
  arrange(year)
```

```{r pc_angola}
# data source: http://apps.who.int/gho/data/node.main.GHEDPVTDpcUSSHA2011?lang=en

pc_angola <- read.csv("angola/gghe-d_pc_angola.csv") 

names(pc_angola) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

pc_angola <- pc_angola %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(pc_angola) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

pc_angola <- pc_angola %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = 2016 - year) %>% 
  arrange(year)
```

```{r external_angola}
# data source: http://apps.who.int/gho/data/node.main.GHEDEXTpcUSSHA2011?lang=en

external_angola <- read.csv("angola/external_angola.csv") 

names(external_angola) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

external_angola <- external_angola %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(external_angola) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

external_angola <- external_angola %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = 2016 - year) %>% 
  arrange(year)
```

```{r private_angola}
# data source: http://apps.who.int/gho/data/node.main.GHEDPVTDpcUSSHA2011?lang=en

private_angola <- read.csv("angola/private_angola.csv") 

names(private_angola) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

private_angola <- private_angola %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(private_angola) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

private_angola <- private_angola %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = 2016 - year) %>% 
  arrange(year)
```

```{r total_angola}
# data source: http://apps.who.int/gho/data/node.main.GHEDCHEpcUSSHA2011?lang=en

total_angola <- read.csv("angola/total_angola.csv") 

names(total_angola) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

total_angola <- total_angola %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(total_angola) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

total_angola <- total_angola %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = 2016 - year) %>% 
  arrange(year)
```

```{r pocket_angola}
# data source:http://apps.who.int/gho/data/node.main.GHEDOOPpcUSSHA2011?lang=en

pocket_angola <- read.csv("angola/pocket_angola.csv") 

names(pocket_angola) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

pocket_angola <- pocket_angola %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(pocket_angola) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

pocket_angola <- pocket_angola %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = 2016 - year) %>% 
  arrange(year)
```

```{r bind}
# I used this site in order to figure out rbind https://stackoverflow.com/questions/10358680/adding-a-one-dataframe-to-the-the-end-of-another-data-frame-in-r and then compiled all the needed data into 

angola_data <- rbind(angola_data, adult_mortality_angola)

angola_data <- rbind(angola_data, gdp_angola)

angola_data <- rbind(angola_data, pc_angola)

angola_data <- rbind(angola_data, external_angola)

angola_data <- rbind(angola_data, private_angola)

angola_data <- rbind(angola_data, total_angola)

angola_data <- rbind(angola_data, pocket_angola)

```

```{r workable data}
#I then changed the groups of metrics into the columns. I added a column on where angola was recieving an IMF loan or not. Information on that found here: https://www.imf.org/external/np/fin/tad/extarr2.aspx?memberKey1=23&date1key=2019-10-31

angola_data_flipped <- acast(angola_data, year ~ metric) 
```

