---
title: "Cleaned Data"
author: "Samuel Lowry"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
#You must run both the angola and namibia rmds completely before this one. 

#I took the data compiled from the namibia and the angola rmds and gave them additional columns. One is country and the other specifies whether or not the year is one where Angola received IMF funding yet.

namibia_data <- namibia_data %>% 
  mutate(country = "Namibia") %>% 
  mutate(SAP = ifelse(year > 2009, "Angola has received IMF money", "Angola has not received IMF money"))

angola_data <- angola_data %>% 
  mutate(country = "Angola") %>% 
  mutate(SAP = ifelse(year > 2009, "Has received IMF money", "Has not received IMF money"))
```

```{r}
# I then joined the two together with inner_join to delete all times where they did not match up. 
combined <- inner_join(angola_data, namibia_data, by = c("metric", "year")) %>% 
  arrange(metric) 
```

```{r}
# I then trimmed the combined data into their two respective countries and gave them proper labels. 

complete_angola_untrimmed <- combined %>% 
  select(metric, year, value.x, country.x, SAP.x)

names(complete_angola_untrimmed) <- c("Metric", "Year", "Value", "Country", "SAP")

complete_namibia_untrimmed <- combined %>% 
  select(metric, year, value.y, country.y, SAP.y)

names(complete_namibia_untrimmed) <- c("Metric", "Year", "Value", "Country", "SAP")
```

```{r}
# I then bound the two together in order to have a central, gapminder-like dataframe. 

complete_data_untrimmed <- rbind(complete_angola_untrimmed, complete_namibia_untrimmed)

```

```{r}
#Here I was able to do some mor eprep pf the data for regression by creating some binaries. In addition, I had to get rid of wonky data that had all zeros for one country or another which would mess up the regression.

explore <- complete_data_untrimmed %>% 
  mutate(SAP = case_when(Country == "Namibia" ~ 0, 
                         Country == "Angola" & Year > 2009 ~ 1,
                         TRUE ~ 0)) %>% 
  mutate(Country = ifelse(Country == "Angola", 1, 0)) %>% 
  filter(Value == 0) %>% 
  group_by(Metric) %>% 
  summarize(sum(Country)/n(),
            n())

#After exploring the data to get rid of the weird zero stuff I made the formal new dataset without them with binaries for regression. 

complete_data_untrimmed_binary <- complete_data_untrimmed %>% 
  mutate(SAP = case_when(Country == "Namibia" ~ 0, 
                         Country == "Angola" & Year > 2009 ~ 1,
                         TRUE ~ 0)) %>% 
  mutate(Country = ifelse(Country == "Angola", 1, 0)) %>%
  subset(Metric != "Coal rents (% of GDP)" 
         & Metric != "Electricity production from natural gas sources (% of total)"
         & Metric != "Electricity production from renewable sources, excluding hydroelectric (% of total)"
         & Metric != "Electricity production from renewable sources, excluding hydroelectric (kWh)"
         & Metric != "Electricity production from coal sources (% of total)"
         & Metric != "Adjusted savings: energy depletion (% of GNI)"
         & Metric != "Adjusted savings: energy depletion (current US$)"
         & Metric != "Adjusted savings: mineral depletion (% of GNI)"
         & Metric != "Adjusted savings: mineral depletion (current US$)"
         & Metric != "Adjusted savings: net forest depletion (% of GNI)"
         & Metric != "Adjusted savings: net forest depletion (current US$)"
         & Metric != "Medium and high-tech exports (% manufactured exports)"
         & Metric != "Mineral rents (% of GDP)"
         & Metric != "Natural gas rents (% of GDP)"
         & Metric != "Oil rents (% of GDP)")
```


```{r}
# After trying to figure out how to get rid of all the needless data in r I resolved that since I am gonna have to read through it all manually, it would be fine to do it in excel, so I used this link to export it! https://datatofish.com/export-dataframe-to-csv-in-r/ . I then went through the data and deleted all that was not needed for my project. This will have to change based upon your filepath!


write.csv(combined,"/Users/samlowry/iCloud Drive (Archive) - 1/Documents/rstudio/gov_1005_final_project/combined_data/combined_untrimmed.csv", 
          row.names = TRUE)
```

```{r}
# I then took the newly cleaned data and put it back into r. After downloading it as a csv and then putting it into the combined_data folder with combined_trimmed as the name. 

combined_trimmed <- read_csv("combined_data/combined_trimmed.csv", col_types = 
                               cols(
                                metric = col_character(),
                                year = col_double(),
                                value.x = col_double(),
                                country.x = col_character(),
                                SAP.x = col_character(),
                                value.y = col_double(),
                                country.y = col_character(),
                                SAP.y = col_character()
                              )) 
```

```{r}
# I then trimmed the combined data into their two respective countries and gave them proper labels. I also changed the years because the 2010 Angola budget was the first one created with IMF loans as the loans took effect in late 2009. 

complete_angola <- combined_trimmed %>% 
  mutate(SAP.x = ifelse(year > 2009, "Has received IMF money", "Has not received IMF money")) %>% 
  select(metric, year, value.x, country.x, SAP.x)

names(complete_angola) <- c("Metric", "Year", "Value", "Country", "SAP")

complete_namibia <- combined_trimmed %>% 
  mutate(SAP.y = ifelse(year > 2009, "Angola has received IMF money", "Angola has not received IMF money")) %>% 
  select(metric, year, value.y, country.y, SAP.y)

names(complete_namibia) <- c("Metric", "Year", "Value", "Country", "SAP")
```

```{r}
# I then bound the two together in order to have a central, gapminder-like dataframe. 

complete_data <- rbind(complete_angola, complete_namibia) 

#Here I gave the trimmed data the same treatment as the untrimmed above to prep it for regression. 

complete_data_binary <- complete_data %>% 
  mutate(SAP = case_when(Country == "Namibia" ~ 0, 
                         Country == "Angola" & Year > 2009 ~ 1,
                         TRUE ~ 0)) %>% 
  mutate(Country = ifelse(Country == "Angola", 1, 0)) %>%
  subset(Metric != "Coal rents (% of GDP)" 
         & Metric != "Electricity production from natural gas sources (% of total)"
         & Metric != "Electricity production from renewable sources, excluding hydroelectric (% of total)"
         & Metric != "Electricity production from renewable sources, excluding hydroelectric (kWh)"
         & Metric != "Electricity production from coal sources (% of total)"
         & Metric != "Adjusted savings: energy depletion (% of GNI)"
         & Metric != "Adjusted savings: energy depletion (current US$)"
         & Metric != "Adjusted savings: mineral depletion (% of GNI)"
         & Metric != "Adjusted savings: mineral depletion (current US$)"
         & Metric != "Adjusted savings: net forest depletion (% of GNI)"
         & Metric != "Adjusted savings: net forest depletion (current US$)"
         & Metric != "Medium and high-tech exports (% manufactured exports)"
         & Metric != "Mineral rents (% of GDP)"
         & Metric != "Natural gas rents (% of GDP)"
         & Metric != "Oil rents (% of GDP)")

#saved the data that is needed for my work in shiny. 

saveRDS(object = complete_data,file = "shiny_demoday/complete_data.rds")

saveRDS(object = complete_data_binary,file = "shiny_demoday/complete_data_binary.rds")
```




