---
title: "Namibia Data"
author: "Samuel Lowry"
date: "11/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(janitor)
library(reshape2)
library(tidyverse)
```

```{r Namibia_data}
# I read in the partially cleaned data attained from https://data.worldbank.org/country/namibia?view=chart

namibia_data <- read.csv("namibia/namibia_worldbank_data.csv")

#I then deleted all the NAs 

namibia_data <- namibia_data%>% 
  na.omit() 

# The problem here is that once the data was imported, the years came up with x in front of them, so I renamed them all. 

names(namibia_data) <- c("metric", 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015)

# I then melted based upon the metric to get the year into a column instead of row. 

namibia_data <- namibia_data %>% 
  melt(id.vars = "metric") 

#I gave the columns better names

names(namibia_data) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

namibia_data <- namibia_data %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = year + 1999) 
```


```{r adult_mortality_namibia}
# data source: http://apps.who.int/gho/data/view.main.1360?lang=en and I got rid of the first row because it was for 2016, and we are just working with 2000-2015

adult_mortality_namibia <- read.csv("namibia/adult_mortality_namibia.csv") 
adult_mortality_namibia = adult_mortality_namibia[-1, ]

#I renamed the years column to lowercase 

names(adult_mortality_namibia) <- c("year", "metric", "value")


#I then specified what everything was and formatted the year.

adult_mortality_namibia <- adult_mortality_namibia %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) 
```

```{r gdp_namibia}
# data source: hhttp://apps.who.int/gho/data/node.main.GHEDGGHEDGDPSHA2011?lang=en

gdp_namibia <- read.csv("namibia/gghe-d_gdp_namibia.csv") 

# The problem here is that once the data was imported, the years came up with x in front of them, so I renamed them all.

names(gdp_namibia) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

gdp_namibia <- gdp_namibia %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(gdp_namibia) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

gdp_namibia <- gdp_namibia %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = year + 1999) 
```

```{r pc_namibia}
# data source: http://apps.who.int/gho/data/node.main.GHEDGGHEDpcUSSHA2011?lang=en

pc_namibia <- read.csv("namibia/gghe-d_pc_namibia.csv") 

names(pc_namibia) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

pc_namibia <- pc_namibia %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(pc_namibia) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

pc_namibia <- pc_namibia %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = year + 1999) 
```

```{r external_namibia}
# data source: http://apps.who.int/gho/data/node.main.GHEDEXTpcUSSHA2011?lang=en

external_namibia <- read.csv("namibia/external_namibia.csv") 

names(external_namibia) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

external_namibia <- external_namibia %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(external_namibia) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

external_namibia <- external_namibia %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = year + 1999) 
```

```{r private_namibia}
# data source: http://apps.who.int/gho/data/node.main.GHEDPVTDpcUSSHA2011?lang=en

private_namibia <- read.csv("namibia/private_namibia.csv") 

names(private_namibia) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

private_namibia <- private_namibia %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(private_namibia) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

private_namibia <- private_namibia %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = year + 1999) 
```

```{r total_namibia}
# data source: http://apps.who.int/gho/data/node.main.GHEDCHEpcUSSHA2011?lang=en

total_namibia <- read.csv("namibia/total_namibia.csv") 

names(total_namibia) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

total_namibia <- total_namibia %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(total_namibia) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

total_namibia <- total_namibia %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = year + 1999) 
```

```{r pocket_namibia}
# data source: http://apps.who.int/gho/data/node.main.GHEDOOPpcUSSHA2011?lang=en

pocket_namibia <- read.csv("namibia/pocket_namibia.csv") 

names(pocket_namibia) <- c("metric", 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000)
 
# I then melted based upon the metric to get the year into a column instead of row. 

pocket_namibia <- pocket_namibia %>% 
    melt(id.vars = "metric")

#I gave the columns better names

names(pocket_namibia) <- c("metric", "year", "value")

#I then specified what everything was and formatted the year.

pocket_namibia <- pocket_namibia %>% 
  transform(metric = as.character(metric)) %>%
  transform(value = as.numeric(value)) %>% 
  transform(year = as.numeric(year)) %>% 
  transform(year = year + 1999) 
```

```{r bind}
# I used this site in order to figure out rbind https://stackoverflow.com/questions/10358680/adding-a-one-dataframe-to-the-the-end-of-another-data-frame-in-r and then compiled all the needed data into 

namibia_data <- rbind(namibia_data, adult_mortality_namibia)

namibia_data <- rbind(namibia_data, gdp_namibia)

namibia_data <- rbind(namibia_data, pc_namibia)

namibia_data <- rbind(namibia_data, external_namibia)

namibia_data <- rbind(namibia_data, private_namibia)

namibia_data <- rbind(namibia_data, total_namibia)

namibia_data <- rbind(namibia_data, pocket_namibia)

```

```{r workable data}
#I then changed the groups of metrics into the columns. I added a column on where namibia was recieving an IMF loan or not. Information on that found here: https://www.imf.org/external/np/fin/tad/extarr2.aspx?memberKey1=23&date1key=2019-10-31

namibia_data_flipped <- acast(namibia_data, year ~ metric) 
```

```{r export data}
# After trying to figure out how to get rid of all the needless data in r I resolved that since I am gonna have to read through it all manually, it would be fine to do it in excel, so I used this link to export it! https://datatofish.com/export-dataframe-to-csv-in-r/

write.csv(namibia_data_flipped,"/Users/samlowry/iCloud Drive (Archive) - 1/Documents/rstudio/angolaproject/namibia/namibia_compiled.csv", row.names = TRUE)
```

