---
title: "Regression"
author: "Samuel Lowry"
date: "12/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(broom)
library(moderndive)
library(purrr)
library(gt)
library(tidyverse)
```

```{r regression}
#Run cleaned data rmd before this! And then namibia and angola data cleaning rmds before that!

#Using the complete binary data that had been trimmed from the cleaned_data.rmd in order to run a regression in order to find the effect of the IMF loans while adjusting for country and year. 

#I then also pulled out the SAP coefficient as well as the p value in order to show significance. 

regression <- complete_data_binary %>%
  group_by(Metric) %>%
  nest() %>% 
  mutate(models = map(data, ~tidy(lm(Value ~ Year + SAP + Country, data = .x)))) %>% 
  mutate(SAP_Coef = map(data, ~tidy(lm(Value ~ Year + SAP + Country, data = .x))$"estimate"[3])) %>% 
  mutate(SAP_Coef = as.numeric(SAP_Coef)) %>% 
  mutate(p_value = map(data, ~tidy(lm(Value ~ Year + SAP + Country, data = .x))$"p.value"[3])) %>% 
  mutate(p_value = as.numeric(p_value))
```

```{r sig}
#I shrunk the dataset down to only metrics that were statistically significant. 

significant_regression <- regression %>% 
  filter(p_value <= .05)


#I saved them to this RDS for work in my shiny app.

saveRDS(object = significant_regression,file = "shiny_app/significant_regression.rds")
```

```{r reg_health_expend_percap}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code. 
# I ignored all of the `cols` is now required warnings because they had no affect on the data. 

#Current health expenditure (WHO) per capita in US$		
reg_health_expend_percap <- significant_regression[14, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_health_expend_percap) %>% 
   tab_header(title = "Current health expenditure per capita in US$") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            ))

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "Current health expenditure (WHO) per capita in US$") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "Current health expenditure per capita",
           y = "US$",
           color = "Structural Adjustment Program")
```

```{r reg_gov_health_expend_percent}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#Domestic general government health expenditure (% of general government expenditure)			
reg_gov_health_expend_percent <- significant_regression[17, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_gov_health_expend_percent) %>% 
   tab_header(title = "Domestic general government health expenditure (% of general government expenditure)") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            ))

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "Domestic general government health expenditure (% of general government expenditure)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "Domestic general government health expenditure",
           y = "Percent of general government expenditure",
           color = "Structural Adjustment Program")
```

```{r reg_gov_health_expend_percap}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#Domestic general government health expenditure (GGHE-D) per capita in US$ (WHO)	
reg_gov_health_expend_percap <- significant_regression[18, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_gov_health_expend_percap) %>% 
   tab_header(title = "Domestic general government health expenditure per capita in US$") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            ))

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "Domestic general government health expenditure (GGHE-D) per capita in US$ (WHO)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "Domestic general government health expenditure per capita",
           y = "US$",
           color = "Structural Adjustment Program")
```

```{r reg_private_health_expend_percap}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#Domestic private health expenditure per capita (current US$) (World Bank)	
reg_private_health_expend_percap <- significant_regression[20, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_private_health_expend_percap) %>% 
   tab_header(title = "Domestic private health expenditure per capita (current US$)") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            ))

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "Domestic private health expenditure per capita (current US$) (World Bank)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "Domestic private health expenditure per capita",
           y = "Current US$",
           color = "Structural Adjustment Program")
```


```{r reg_gdp}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#GDP (constant 2010 US$)
reg_gdp <- significant_regression[21, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_gdp) %>% 
   tab_header(title = "GDP (constant 2010 US$)") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            ))

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "GDP (constant 2010 US$)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "GDP",
           y = "Constant 2010 US$",
           color = "Structural Adjustment Program")
```


```{r reg_gdp_growth}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#GDP growth (annual %)
reg_gdp_growth <- significant_regression[22, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_gdp_growth) %>% 
   tab_header(title = "GDP growth (Annual Percent)") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            ))

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "GDP growth (annual %)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "GDP growth",
           y = "Annual Percent",
           color = "Structural Adjustment Program")
```


```{r reg_gdp_percap}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#GDP per capita (constant 2010 US$)	
reg_gdp_percap <- significant_regression[23, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_gdp_percap) %>% 
   tab_header(title = "GDP per capita (constant 2010 US$)") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            ))

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "GDP per capita (constant 2010 US$)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "GDP per capita",
           y = "Constant 2010 US$",
           color = "Structural Adjustment Program")
```


```{r reg_gdp_percap_growth}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#GDP per capita growth (annual %)
reg_gdp_percap_growth <- significant_regression[24, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_gdp_percap_growth) %>% 
   tab_header(title = "GDP per capita growth (annual %)") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            ))

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "GDP per capita growth (annual %)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "GDP per capita growth",
           y = "Annual Percent",
           color = "Structural Adjustment Program")
```


```{r reg_gni}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#GNI (constant 2010 US$)	
reg_gni <- significant_regression[25, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_gni) %>% 
   tab_header(title = "GNI (constant 2010 US$)") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            ))

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "GNI (constant 2010 US$)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "GNI",
           y = "Constant 2010 US$",
           color = "Structural Adjustment Program")
```


```{r reg_tax}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#Taxes on income, profits and capital gains (% of revenue)	
reg_tax <- significant_regression[52, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_tax) %>% 
   tab_header(title = "Taxes on income, profits and capital gains (% of revenue)") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            )) 

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "Taxes on income, profits and capital gains (% of revenue)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "Taxes on income, profits and capital gains",
           y = "Percent of Revenue",
           color = "Structural Adjustment Program")
```


```{r reg_pocket_percent}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#Out-of-pocket expenditure (% of current health expenditure)	
reg_pocket_percent <- significant_regression[45, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_pocket_percent) %>% 
   tab_header(title = "Out-of-pocket expenditure (% of current health expenditure)") %>% 
  cols_label(term = "",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            )) 

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "Out-of-pocket expenditure (% of current health expenditure)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "Out-of-pocket expenditure",
           y = "Percent of current health expenditure",
           color = "Structural Adjustment Program")
```


```{r reg_pocket_percap}
#Here I pulled certain important metrics and created the proper tables for them all as well as graphs to show in my shiny app. I will pull over the code.

#Out-of-pocket expenditure per capita (current US$) (World Bank)	
reg_pocket_percap <- significant_regression[47, 3] %>% 
  unnest()

#I bolded the SAP coefficient 
gt(reg_pocket_percap) %>% 
   tab_header(title = "Out-of-pocket expenditure per capita (current US$)") %>% 
  cols_label(
    term = " ",
    estimate = "Coefficient",
    std.error = "Standard Error",
    statistic = "Statistic",
    p.value = "P Value") %>% 
  tab_style(style = cell_text(weight = "bold"),
            locations = cells_data(
              columns = vars(estimate),
              rows = 3
            )) 

#plot just like the shiny drop down
complete_data %>% 
      filter(Metric == "Out-of-pocket expenditure per capita (current US$) (World Bank)") %>% 
      ggplot(aes(x = Year, y = Value, color = SAP)) +
      geom_point() +
      geom_smooth(method = "lm", se = FALSE) +
      facet_wrap(~ Country) +
      labs(title = "Out-of-pocket expenditure per capita",
           y = "Current US$",
           color = "Structural Adjustment Program")
```

